const tailwindcssAnimate = require("tailwindcss-animate");
const containerQueries = require("@tailwindcss/container-queries");

module.exports = {
  darkMode: ["class"],
  /* Safelist Riibon design-system tokens that are commonly composed via state
     (variant props, theme-driven choice, etc.) so dynamic class names never
     silently drop. Adds ~3KB of CSS — worth it for system reliability. */
  safelist: [
    { pattern: /^shadow-rb-(xs|sm|md|lg|xl|ring|offset-lg|offset-sm)$/ },
    { pattern: /^animate-rb-(pulse|blink|slide-up|slide-left|fade-in|scan|grow|marquee|shimmer|fade-up)$/ },
    { pattern: /^(ease|duration)-rb(-(in|out|in-out|fast|base|slow|slower))?$/ },
    { pattern: /^rounded-rb-(xs|sm|md|lg|xl|2xl|pill)$/ },
    { pattern: /^bg-rb-seq-(100|200|300|400|500|600|700)$/ },
    { pattern: /^bg-rb-div-(neg-3|neg-2|neg-1|0|pos-1|pos-2|pos-3)$/ },
    { pattern: /^bg-rb-viz-[1-8]$/ },
    { pattern: /^text-rb-(display|h1|h2|h3|body-lg|body|body-sm|caption|code|micro|micro-sm|micro-md|mini|mini-sm|cell)$/ },
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Geist', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Bricolage Grotesque', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'Menlo', 'Monaco', 'monospace'],
        serif: ['Instrument Serif', 'ui-serif', 'Georgia', 'serif'],
      },
      fontSize: {
        "rb-display":  ["var(--rb-text-display)",  { lineHeight: "var(--rb-text-display-lh)",  letterSpacing: "-0.02em", fontWeight: "600" }],
        "rb-h1":       ["var(--rb-text-h1)",       { lineHeight: "var(--rb-text-h1-lh)",       letterSpacing: "-0.02em", fontWeight: "600" }],
        "rb-h2":       ["var(--rb-text-h2)",       { lineHeight: "var(--rb-text-h2-lh)",       letterSpacing: "-0.015em", fontWeight: "600" }],
        "rb-h3":       ["var(--rb-text-h3)",       { lineHeight: "var(--rb-text-h3-lh)",       letterSpacing: "-0.01em",  fontWeight: "600" }],
        "rb-body-lg":  ["var(--rb-text-body-lg)",  { lineHeight: "var(--rb-text-body-lg-lh)",  letterSpacing: "-0.005em", fontWeight: "400" }],
        "rb-body":     ["var(--rb-text-body)",     { lineHeight: "var(--rb-text-body-lh)",     letterSpacing: "0",        fontWeight: "400" }],
        "rb-body-sm":  ["var(--rb-text-body-sm)",  { lineHeight: "var(--rb-text-body-sm-lh)",  letterSpacing: "0",        fontWeight: "400" }],
        "rb-caption":  ["var(--rb-text-caption)",  { lineHeight: "var(--rb-text-caption-lh)",  letterSpacing: "0.01em",   fontWeight: "500" }],
        "rb-code":     ["var(--rb-text-code)",     { lineHeight: "var(--rb-text-code-lh)",     letterSpacing: "-0.01em",  fontWeight: "500" }],
        /* Micro-typography ramp — sub-12px tokens used for chrome chips
           (BETA tag, count pills, cell metadata, kbd hints). Tokenised
           so designers can rebalance one global setting instead of
           chasing 50+ `text-[Npx]` arbitrary-value escapes. */
        "rb-micro":    ["9px",    { lineHeight: "1.2",  fontWeight: "500" }],
        "rb-micro-sm": ["10px",   { lineHeight: "1.2",  fontWeight: "500" }],
        "rb-micro-md": ["10.5px", { lineHeight: "1.25", fontWeight: "500" }],
        "rb-mini":     ["11px",   { lineHeight: "1.3",  fontWeight: "500" }],
        "rb-mini-sm":  ["11.5px", { lineHeight: "1.3",  fontWeight: "500" }],
        "rb-cell":     ["12.5px", { lineHeight: "1.4",  fontWeight: "400" }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        "tertiary-foreground": "hsl(var(--tertiary-foreground))",
        icon: {
          DEFAULT: "hsl(var(--icon))",
          muted: "hsl(var(--icon-muted))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        chat: {
          user: "hsl(var(--chat-user-bg))",
          assistant: "hsl(var(--chat-assistant-bg))",
          input: "hsl(var(--chat-input-bg))",
          hover: "hsl(var(--chat-hover))",
        },
        /* Riibon brand palette — direct-access utilities (bg-rb-blue-500, text-rb-ink, …)
           Scales that need opacity modifiers (e.g. bg-rb-coral-500/10) are wired via
           `hsl(var(--rb-<name>-hsl) / <alpha-value>)` — the triplets live in index.css. */
        rb: {
          blue: {
            DEFAULT: "var(--rb-blue)",
            50: "var(--rb-blue-50)",
            100: "var(--rb-blue-100)",
            200: "var(--rb-blue-200)",
            300: "hsl(var(--rb-blue-300-hsl) / <alpha-value>)",
            400: "var(--rb-blue-400)",
            500: "hsl(var(--rb-blue-500-hsl) / <alpha-value>)",
            600: "var(--rb-blue-600)",
            700: "var(--rb-blue-700)",
            800: "var(--rb-blue-800)",
            900: "var(--rb-blue-900)",
          },
          coral: {
            DEFAULT: "var(--rb-coral)",
            50: "var(--rb-coral-50)",
            100: "var(--rb-coral-100)",
            200: "var(--rb-coral-200)",
            300: "var(--rb-coral-300)",
            400: "hsl(var(--rb-coral-400-hsl) / <alpha-value>)",
            500: "hsl(var(--rb-coral-500-hsl) / <alpha-value>)",
            600: "hsl(var(--rb-coral-600-hsl) / <alpha-value>)",
            700: "var(--rb-coral-700)",
            800: "var(--rb-coral-800)",
          },
          yellow: {
            DEFAULT: "var(--rb-yellow)",
            50: "var(--rb-yellow-50)",
            100: "var(--rb-yellow-100)",
            200: "var(--rb-yellow-200)",
            300: "hsl(var(--rb-yellow-300-hsl) / <alpha-value>)",
            400: "var(--rb-yellow-400)",
            500: "hsl(var(--rb-yellow-500-hsl) / <alpha-value>)",
            600: "hsl(var(--rb-yellow-600-hsl) / <alpha-value>)",
          },
          cream: {
            DEFAULT: "var(--rb-cream)",
            50: "var(--rb-cream-50)",
            100: "var(--rb-cream-100)",
            200: "var(--rb-cream-200)",
            300: "var(--rb-cream-300)",
          },
          ink: {
            DEFAULT: "var(--rb-ink)",
            50: "var(--rb-neutral-50)",
            100: "var(--rb-neutral-100)",
            200: "var(--rb-neutral-200)",
            300: "var(--rb-neutral-300)",
            400: "var(--rb-neutral-400)",
            500: "var(--rb-neutral-500)",
            600: "var(--rb-neutral-600)",
            700: "var(--rb-neutral-700)",
            800: "var(--rb-neutral-800)",
            900: "var(--rb-neutral-900)",
            950: "var(--rb-neutral-950)",
          },
          neutral: {
            0: "var(--rb-neutral-0)",
            25: "var(--rb-neutral-25)",
            50: "var(--rb-neutral-50)",
            100: "var(--rb-neutral-100)",
            200: "var(--rb-neutral-200)",
            300: "var(--rb-neutral-300)",
            400: "hsl(var(--rb-neutral-400-hsl) / <alpha-value>)",
            500: "hsl(var(--rb-neutral-500-hsl) / <alpha-value>)",
            600: "var(--rb-neutral-600)",
            700: "var(--rb-neutral-700)",
            800: "var(--rb-neutral-800)",
            900: "var(--rb-neutral-900)",
            950: "var(--rb-neutral-950)",
          },
          forest: {
            50: "var(--rb-forest-50)",
            100: "var(--rb-forest-100)",
            300: "var(--rb-forest-300)",
            500: "hsl(var(--rb-forest-500-hsl) / <alpha-value>)",
            700: "hsl(var(--rb-forest-700-hsl) / <alpha-value>)",
          },
          terracotta: {
            50: "var(--rb-terracotta-50)",
            300: "var(--rb-terracotta-300)",
            500: "hsl(var(--rb-terracotta-500-hsl) / <alpha-value>)",
            700: "hsl(var(--rb-terracotta-700-hsl) / <alpha-value>)",
          },
          sage: {
            100: "var(--rb-sage-100)",
            300: "var(--rb-sage-300)",
            500: "var(--rb-sage-500)",
          },
          plum: {
            100: "var(--rb-plum-100)",
            300: "hsl(var(--rb-plum-300-hsl) / <alpha-value>)",
            500: "hsl(var(--rb-plum-500-hsl) / <alpha-value>)",
          },
          ochre: {
            100: "var(--rb-ochre-100)",
            300: "var(--rb-ochre-300)",
            500: "var(--rb-ochre-500)",
          },
          success: "var(--rb-success)",
          "success-bg": "var(--rb-success-bg)",
          "success-border": "var(--rb-success-border)",
          "success-strong": "var(--rb-success-strong)",
          warning: "var(--rb-warning)",
          "warning-bg": "var(--rb-warning-bg)",
          "warning-border": "var(--rb-warning-border)",
          "warning-strong": "var(--rb-warning-strong)",
          error: "var(--rb-error)",
          "error-bg": "var(--rb-error-bg)",
          "error-border": "var(--rb-error-border)",
          "error-strong": "var(--rb-error-strong)",
          info: "var(--rb-info)",
          "info-bg": "var(--rb-info-bg)",
          "info-border": "var(--rb-info-border)",
          "info-strong": "var(--rb-info-strong)",
          highlight: "var(--rb-highlight)",
          "highlight-bg": "var(--rb-highlight-bg)",
          "highlight-border": "var(--rb-highlight-border)",
          /* Surface tiers */
          "surface-page":     "var(--rb-surface-page)",
          "surface-section":  "var(--rb-surface-section)",
          "surface-card":     "var(--rb-surface-card)",
          "surface-elevated": "var(--rb-surface-elevated)",
          "surface-inline":   "var(--rb-surface-inline)",
          "surface-ink":      "var(--rb-surface-ink)",
          /* Border tiers */
          "border-subtle": "var(--rb-border-subtle)",
          "border-DEFAULT": "var(--rb-border)",
          "border-strong": "var(--rb-border-strong)",
          /* Chart chrome tokens (Recharts grid/axis/tooltip) */
          "grid": "var(--rb-grid)",
          "axis": "var(--rb-axis)",
          "tooltip-bg": "var(--rb-tooltip-bg)",
          "tooltip-fg": "var(--rb-tooltip-fg)",
          /* Text tiers */
          "text-primary":   "var(--rb-text-primary)",
          "text-secondary": "var(--rb-text-secondary)",
          "text-tertiary":  "var(--rb-text-tertiary)",
          "text-inverse":   "var(--rb-text-inverse)",
          "text-accent":    "var(--rb-text-accent)",
          "text-placeholder": "var(--rb-text-placeholder)",
          /* Sequential viz ramp */
          "seq-100": "var(--rb-seq-100)",
          "seq-200": "var(--rb-seq-200)",
          "seq-300": "var(--rb-seq-300)",
          "seq-400": "var(--rb-seq-400)",
          "seq-500": "var(--rb-seq-500)",
          "seq-600": "var(--rb-seq-600)",
          "seq-700": "var(--rb-seq-700)",
          /* Diverging viz ramp */
          "div-neg-3": "var(--rb-div-neg-3)",
          "div-neg-2": "var(--rb-div-neg-2)",
          "div-neg-1": "var(--rb-div-neg-1)",
          "div-0":     "var(--rb-div-0)",
          "div-pos-1": "var(--rb-div-pos-1)",
          "div-pos-2": "var(--rb-div-pos-2)",
          "div-pos-3": "var(--rb-div-pos-3)",
          /* Categorical viz */
          "viz-1": "var(--rb-viz-1)",
          "viz-2": "var(--rb-viz-2)",
          "viz-3": "var(--rb-viz-3)",
          "viz-4": "var(--rb-viz-4)",
          "viz-5": "var(--rb-viz-5)",
          "viz-6": "var(--rb-viz-6)",
          "viz-7": "var(--rb-viz-7)",
          "viz-8": "var(--rb-viz-8)",
        },
      },
      boxShadow: {
        "rb-xs": "var(--rb-shadow-xs)",
        "rb-sm": "var(--rb-shadow-sm)",
        "rb-md": "var(--rb-shadow-md)",
        "rb-lg": "var(--rb-shadow-lg)",
        "rb-xl": "var(--rb-shadow-xl)",
        "rb-ring": "var(--rb-ring)",
        /* Offset hard-shadow — marketing-register brand element (D4). */
        "rb-offset-lg": "var(--rb-shadow-offset-lg)",
        "rb-offset-sm": "var(--rb-shadow-offset-sm)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "rb-xs":   "var(--rb-radius-xs)",
        "rb-sm":   "var(--rb-radius-sm)",
        "rb-md":   "var(--rb-radius-md)",
        "rb-lg":   "var(--rb-radius-lg)",
        "rb-xl":   "var(--rb-radius-xl)",
        "rb-2xl":  "var(--rb-radius-2xl)",
        "rb-pill": "var(--rb-radius-pill)",
      },
      spacing: {
        "rb-1":  "var(--rb-space-1)",
        "rb-2":  "var(--rb-space-2)",
        "rb-3":  "var(--rb-space-3)",
        "rb-4":  "var(--rb-space-4)",
        "rb-5":  "var(--rb-space-5)",
        "rb-6":  "var(--rb-space-6)",
        "rb-7":  "var(--rb-space-7)",
        "rb-8":  "var(--rb-space-8)",
        "rb-9":  "var(--rb-space-9)",
        "rb-10": "var(--rb-space-10)",
        "rb-12": "var(--rb-space-12)",
        "rb-16": "var(--rb-space-16)",
      },
      transitionTimingFunction: {
        rb: "var(--rb-ease)",
        "rb-in": "var(--rb-ease-in)",
        "rb-out": "var(--rb-ease-out)",
        "rb-in-out": "var(--rb-ease-in-out)",
      },
      transitionDuration: {
        "rb-fast": "var(--rb-dur-fast)",
        "rb-base": "var(--rb-dur-base)",
        "rb-slow": "var(--rb-dur-slow)",
        "rb-slower": "var(--rb-dur-slower)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "rb-pulse": {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "1" },
        },
        "rb-blink": {
          "0%, 49%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
        "rb-slide-up": {
          from: { transform: "translateY(6px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        "rb-slide-left": {
          from: { transform: "translateX(18px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "rb-fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "rb-scan": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(200%)" },
        },
        "rb-grow": {
          from: { transform: "scaleY(0)" },
          to: { transform: "scaleY(1)" },
        },
        "rb-marquee": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(-50%)" },
        },
        "rb-shimmer": {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition:  "200% 0" },
        },
        "rb-fade-up": {
          from: { opacity: "0", transform: "translateY(6px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "rb-pulse": "rb-pulse 1.4s var(--rb-ease) infinite",
        "rb-blink": "rb-blink 1s steps(1) infinite",
        "rb-slide-up": "rb-slide-up 0.3s var(--rb-ease) both",
        "rb-slide-left": "rb-slide-left 0.3s var(--rb-ease) both",
        "rb-fade-in": "rb-fade-in 0.3s var(--rb-ease) both",
        "rb-scan": "rb-scan 1.6s var(--rb-ease) infinite",
        "rb-grow": "rb-grow 0.3s var(--rb-ease) both",
        "rb-marquee": "rb-marquee 24s linear infinite",
        "rb-shimmer": "rb-shimmer 1.4s linear infinite",
        "rb-fade-up": "rb-fade-up 0.4s var(--rb-ease-out) both",
      },
    },
  },
  plugins: [tailwindcssAnimate, containerQueries],
};
